---
title: "Analises Descritivas"
author: "LucianoRogerio e HenriqueBernardino"
date: "2021-10-12"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

[Wrong Page?](index.html)

## Descriptive analysis

### Foliar Diseases

```{r reading the foliar disease data, message=FALSE}
suppressMessages(library(tidyverse))
PhenoData <- readRDS(here::here("output", "DadosFenotipicosv2.RDS"))
```


#### Fig 1. Barplots of cassava foliar disease traits
```{r figure1, echo = FALSE, warning = FALSE}
PhenoData %>% filter(!is.na(traits), !is.na (Y)) %>%
  group_by(traits, Y) %>%
  summarise(y = n()) %>%
  ggplot(aes(x = traits, y = Y, fill = as.character(Y))) +
  scale_fill_brewer(type = "div", palette = 7) +
  geom_bar(position = "fill", stat = "identity") +
  guides(fill = guide_legend(title = "Score"))
```

#### Fig 2. Distribution plots of cassava foliar disease traits
```{r figure2, echo = FALSE, warning = FALSE}
PhenoData %>% ggplot(aes(x = Y)) + geom_density(adjust = 2.5, fill = "darkgreen") + 
  facet_wrap(~ traits, scales = "free_x") + xlab("Scores") +
  theme(legend.position="none",
        panel.spacing = unit(0.1, "lines"),
        axis.ticks.x=element_blank())
```


### Yield Traits

```{r reading the yield data, message=FALSE}
suppressMessages(library(tidyverse))
PhenoData <- readRDS(here::here("output", "DadosFenotipicos.RDS"))
```


#### Fig 3. Distribution plots of cassava yield traits
```{r figure3, echo = FALSE, warning = FALSE}
PhenoData %>% dplyr::filter(Trait %in% c("PTR", "PPA", "NR")) %>%
  ggplot(aes(x = y)) + geom_density(adjust = 2.5, fill = "darkgreen") + 
  facet_wrap(~ Trait, scales = "free") +
  theme(legend.position="none",
        panel.spacing = unit(0.1, "lines"),
        axis.ticks.x=element_blank())
```

### Vigor evaluations

#### Fig 4. Barplots of cassava vigor
```{r figure4, echo = FALSE, warning = FALSE}
PhenoData %>% filter(!is.na(Trait), !is.na (y), Trait %in% c("Vigor", "Vigor45D",
                                                             "Vigor6M", "Vigor12M")) %>%
  group_by(Trait, y) %>%
  dplyr::summarise(Y = n()) %>%
  ggplot(aes(x = Trait, y = Y, fill = as.character(y))) +
  scale_fill_brewer(type = "div", palette = 7) +
  geom_bar(position = "fill", stat = "identity") +
  guides(fill = guide_legend(title = "Score"))
```

#### Fig 5. Distribution plots of cassava vigor
```{r figure5, echo = FALSE, warning = FALSE}
PhenoData %>% filter(Trait %in% c("Vigor", "Vigor45D",
                                  "Vigor6M", "Vigor12M")) %>%
  ggplot(aes(x = y)) + geom_density(adjust = 2.5, fill = "darkgreen") + 
  facet_wrap(~ Trait) +
  theme(legend.position="none",
        panel.spacing = unit(0.1, "lines"),
        axis.ticks.x=element_blank())
```


[Next page](AnalisesModelosMistos.html)

[Back to home](index.html)
